## mode （最頻値）

In [5]:
from scipy import stats

mode, count = stats.mode(
    [3,6,3,8,5,9,1,2,7,5,9,8]
)
# 最頻値が複数ある場合は，最も小さい値を返す
print(mode)
print(count)

[3]
[2]


In [8]:
import numpy as np
from scipy import stats

array = np.array([
    [1,3,6,8],
    [3,4,3,5],
    [6,5,9,6],
    [1,9,9,2],
])
# 縦軸で最頻値を計算する
mode, count = stats.mode(array, axis=0)
print(mode)
print(count)

[[1 3 9 2]]
[[2 1 2 1]]


In [10]:
# 横軸で最頻値を計算する
mode, count = stats.mode(array, axis=1)
print(mode)
print(count)

[[1]
 [3]
 [6]
 [9]]
[[1]
 [2]
 [2]
 [2]]
