## 標準化（平均0, 標準偏差1にする）

In [4]:
import numpy as np
items = [21,9,0,54,78,69,18,94,38,76]

In [5]:
mean = np.mean(items)
std = np.std(items)

# 標準化
z = (items - mean) / std

In [8]:
print('standardized items(z): {}'.format(z))
print('mean: {:.2f}'.format(np.mean(z)))
print('std: {}'.format(np.std(z)))

standardized items(z): [-0.78989564 -1.17365061 -1.46146683  0.26543052  1.03294045  0.74512423
 -0.88583438  1.54461374 -0.24624277  0.96898129]
mean: -0.00
std: 0.9999999999999999


In [10]:
# sklearnを利用
from sklearn.preprocessing import StandardScaler

In [19]:
items_arr = np.array(items)
# shape: https://deepage.net/features/numpy-shape.html
print('items_arr shape: {}'.format(items_arr.shape))
print(items_arr)

items_arr shape: (10,)
[21  9  0 54 78 69 18 94 38 76]


In [18]:
# expand_dims(): https://note.nkmk.me/python-numpy-newaxis/
expanded_items = np.expand_dims(items_arr, axis=-1)
print('reshaped items_arr shape: {}'.format(expanded_items.shape))
print(expanded_items)

reshaped items_arr shape: (10, 1)
[[21]
 [ 9]
 [ 0]
 [54]
 [78]
 [69]
 [18]
 [94]
 [38]
 [76]]


In [20]:
# インスタンス作成
scaler = StandardScaler()
# fit_transformの引数は，rank2のndarrayの必要あり
scaled = scaler.fit_transform(expanded_items)
print(scaled)

[[-0.78989564]
 [-1.17365061]
 [-1.46146683]
 [ 0.26543052]
 [ 1.03294045]
 [ 0.74512423]
 [-0.88583438]
 [ 1.54461374]
 [-0.24624277]
 [ 0.96898129]]
